// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/scorecasa-client/Portal.tsx": () => import("../components/mockups/scorecasa-client/Portal.tsx")
};
